## Research Experience  {#experience-research}

**Graduate Research Assistant** (2015–Present)    
Nebraska Cooperative Fish and Wildlife Research Unit | University of Nebraska-Lincoln    

* Explore methods for detecting and predicting regime shifts on long-term, citizen science data.   
* Identify indicator species for ecosystem regime shift prediction.  
* Maintain clear communication with international collaborators.  
* Work with military base scientists to collect data.   
* Write quarterly reports for Department of Defense.  
  
**Graduate Research Assistant** (2013-2015)  
Department of Wildlife Ecology and Conservation | University of Florida  

* Use open-source data to monitor invasive species' population trends.  
* Development of occupancy models of non-native bird speces in urban areas.  


**GIS and Avian Ecology Intern** (2013)  
Fish and Wildlife Research Institute | Florida Fish and Wildlife Research Conservation Commission    

* Investigated effects of agriculture and urbanization on American Kestrel (*Falco sparverius*) nest success.   


**Research Assistant** (2012-2013) 
Sieving Avian Ecology and Conservation Lab | University of Florida    

* Investigated alignment of predation risk perception and predation risk of small forest birds.  
* Managed seasonal bird danding database and banding supplies.  
  
**Smithsonian Fellow and Florida Crew Leader** (2011-2013)  
Neighborhood Nestwatch Program  | Smithsonian Migratory Bird Center  

* Targeted capture and banding of select species in participants' backyards.  
* Banding demonstrations at local youth organizations.  
* Organized and trained banding technicians.  


**Project Volunteer  ** (2012)  
Ordway Lab of Ecosystem Conservation | Univeristy of Florida  

* Transcribed voice-recorded, behavioral foraging data.
* Identified louse from lowland manakins and flycatcher specimens. 